#!/bin/bash

#Welcome message for the Directory Usage Tool.

echo " This is the File Directory usage report tool. Version 1.0"
sleep 1
read -p "Please enter the absolute path of the directory you'd like usage stats for: " dir
sleep 1

#Report Generation
touch /home/balogunN/report.txt
echo "Directory Usage Report" >> /home/balogunN/report.txt
echo "This report was generated on $(date)" >> /home/balogunN/report.txt
echo "Directory: $dir" >> /home/balogunN/report.txt
echo "List of files" >> /home/balogunN/report.txt
ls -l $dir >> /home/balogunN/report.txt
du -sh $dir >> /home/balogunN/report.txt
sleep 1

#End of Script
echo "Done. Report has been generated for $dir. Please check your home directory"
